# nginx-app.conf (ou default.conf - o nome não importa tanto quanto o CONTEÚDO)
# Este arquivo será copiado para /etc/nginx/conf.d/

server {
  listen 80; # Nginx vai ouvir na porta 80 dentro do container
  server_name localhost; # Pode ser seu domínio em produção

  root /usr/share/nginx/html; 

  location / {
    try_files $uri $uri/ /index.html; 
  }

  location ~* \.(css|js|gif|png|jpg|jpeg|svg|woff|woff2|ttf|ico|eot)$ {
      expires 1y;
      add_header Cache-Control "public";
  }

  error_page 500 502 503 504 /50x.html;
  location = /50x.html {
    root /usr/share/nginx/html;
  }
}