# docker-compose.yml
version: '3.8'

services:
  backend:
    restart: always # Garante que o backend reinicie com o Docker
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      PORT: ${PORT}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge