version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80" # Mapeia a porta 80 do container para a porta 80 da sua máquina
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge