# docker-compose.yml
version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-local
    ports:
      - "27017:27017" # Mapeia a porta padrão do MongoDB
    volumes:
      - mongodb_data:/data/db # Volume persistente para os dados
    environment:
      # Opcional: Defina usuário e senha para maior segurança (descomente e configure)
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    restart: always # Garante que o MongoDB reinicie com o Docker
    networks:
      - app-network # Rede para comunicação entre containers

volumes:
  mongodb_data: # Define o volume persistente

networks:
  app-network:
    driver: bridge