# docker-compose.yml
version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb-local
    ports:
      - "27017:27017"
    volumes:
      # Use um bind mount para o diretório no seu SSD
      - D:\_Shared_files\_Amontoa-Server\mongodb_data:/data/db # <--- ALTERE ESTA LINHA
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - app-network

# Você NÃO precisa mais da seção 'volumes' se estiver usando apenas o bind mount
# volumes:
#   mongodb_data:

networks:
  app-network:
    driver: bridge